name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    uses: Migracao-NET/sara_pipelines_templates/.github/workflows/pipeline_dotnetfw.yml@main
    with:
      dotnet-version: '4.7.2'
