name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    uses: Migracao-NET/sara_pipelines_templates/.github/workflows/ci_dotnetfw.yml@main
    with:
      org_lower: ${{ github.repository_owner }}
    secrets: inherit
